### ISSUE TITLE
Add a name field to the `APIToken` model

### ISSUE THREAD

**Issue by jafacakes2011** [Wharton-Interactive/simpl-cloud#1]
https://github.com/Wharton-Interactive/simpl-cloud/blob/main/simpl/models.py#L529

Add a name field so that it is easier to differentiate between keys and where they are being used.

Tasks:
 - Add name field to `APIToken` model
 - Make sure you can add/edit the field in Django Admin
 - Make sure the name field appears in the Django Admin list view

**Comment by SmileyChris** [comment]
This was done in 4f2de63e6b0c86223c98a55c87b9c1b33a31d7e4
